site_name: 'Amulet Docs'
site_description: 'Everything you need to know about developing for the Amulet Network.'

# Repository
repo_name: 'amulet-network/amulet-network-docs'
repo_url: 'https://github.com/amulet-network/amulet-network-docs'

# Copyright
copyright: 'Copyright &copy; 2017 Amulet R&D'

# Documentation and theme
theme: 'material'

site_favicon: 'images/favicon.ico'

pages:
    - Home: index.md

# Options
extra:
  logo: 'images/logo.png'
  palette:
    primary: 'amulet'
    accent: 'amulet'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/amulet-network'
    - type: 'twitter'
      link: 'https://twitter.com/amuletnetwork'
    - type: 'facebook'
      link: 'https://www.facebook.com/amuletnetwork'

# Google Analytics
google_analytics:
  - 'UA-104487472-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)